#pragma once

#include <string>

enum error_code {
    ERR_ID_EXPECTED,
    ERR_LBRACE_EXPECTED,
    ERR_RBRACE_EXPECTED,
    ERR_LBRACKET_EXPECTED,
    ERR_RBRACKET_EXPECTED,
    ERR_LPAREN_EXPECTED,
    ERR_RPAREN_EXPECTED,
    ERR_SEMICOLON_EXPECTED,
    ERR_MODULE_NAME_EXPECTED,
    ERR_PARAM_TYPE_EXPECTED,
    ERR_PARAM_NAME_EXPECTED,
    ERR_FORWARD_DECL_UNSUPPORTED,
    ERR_UNEXPECTED_TOKEN_PRIMARY_EXPR,
    ERR_INCOMPLETE_ESCAPE_SEQ,
    ERR_CONSTRUCTOR_CALLS_ITSELF,
    ERR_MEMBER_TYPE_EXPECTED,
    ERR_NESTED_FUNCTION_NOT_ALLOWED,
    ERR_PARAM_VOID_TYPE,
    ERR_FUNC_ALREADY_DEFINED,
    ERR_NESTED_CONSTRUCTOR_NOT_ALLOWED,
    ERR_CONSTRUCTOR_OUTSIDE_TYPE,
    ERR_CONSTRUCTOR_OVERLOAD_EXISTS,
    ERR_VARIABLE_VOID_TYPE,
    ERR_VARIABLE_ALREADY_DECLARED,
    ERR_TYPE_ALREADY_DEFINED,
    ERR_NESTED_TYPE_DECLARATION_NOT_ALLOWED,
    ERR_STRUCT_CONTAINS_METHOD,
    ERR_INTERFACE_CONTAINS_CONSTRUCTOR,
    ERR_INTERFACE_CONTAINS_MEMBER_VAR,
    ERR_DUPLICATE_PARAMETER,
    ERR_UNKNOWN_IDENTIFIER,
    ERR_UNKNOWN_FUNCTION,
    ERR_UNKNOWN_TYPE,
    ERR_NO_MATCHING_CONSTRUCTOR,
    ERR_TOO_MANY_INITIALIZER_VALUES,
    ERR_TYPE_MISMATCH_INITIALIZER,
    ERR_INTERFACE_INITIALIZER,
    ERR_ARRAY_INITIALIZER_UNSUPPORTED,
    ERR_INVALID_INITIALIZER_LIST_USAGE,
    ERR_TYPE_ASSIGNMENT_MISMATCH,
    ERR_NO_MATCHING_OPERATOR,
    ERR_TYPE_NOT_DEFINED,
    ERR_MEMBER_NAME_EXPECTED,
    ERR_NO_MEMBER_WITH_NAME,
    ERR_NO_MATCHING_OPERATOR_BUILTIN_USER,
    ERR_LOGICAL_NOT_BOOLEAN_ONLY,
    ERR_NEGATE_NUMERIC_ONLY,
    ERR_INCREMENT_INTEGER_ONLY,
    ERR_DECREMENT_INTEGER_ONLY,
    ERR_BASE_NOT_INDEXABLE,
    ERR_INDEXER_NOT_INTEGER,
    ERR_NO_MATCHING_FUNCTION,
    ERR_NO_MATCHING_CONSTRUCTOR_ARGS,
    ERR_IF_CONDITION_NOT_BOOLEAN,
    ERR_FOR_CONDITION_NOT_BOOLEAN,
    ERR_WHILE_CONDITION_NOT_BOOLEAN,
    ERR_RETURN_OUTSIDE_FUNCTION,
    ERR_CONSTRUCTOR_RETURNS_VALUE,
    ERR_VOID_FUNCTION_RETURNS_VALUE,
    ERR_FUNCTION_MUST_RETURN_VALUE,
    ERR_FUNCTION_RETURN_TYPE_MISMATCH,
    ERR_NOT_ALL_PATHS_RETURN_VALUE,
    ERR_NO_METHOD_WITH_NAME,
    ERR_THIS_OUTSIDE_NONSTATIC_METHOD,
    ERR_INVALID_FLOAT_MULTIPLE_DECIMAL,
    ERR_INVALID_FLOAT_NO_DIGITS_AFTER_DECIMAL,
    ERR_UNTERMINATED_CHAR_LITERAL,
    ERR_UNTERMINATED_STRING_LITERAL,
    ERR_TOO_MANY_CHARS_IN_CHAR_LITERAL,
    ERR_EXPRESSION_EXPECTED,
    ERR_UNEXPECTED_IDENTIFIER,
    ERR_DECLARATION_EXPECTED,
    ERR_UNINITIALIZED_VARIABLE,
    ERR_MEMBER_ACCESS_ON_NONCOMPOSITE,
    ERR_PARAMETER_EXPECTED,
    ERR_NO_CONVERSION_EXISTS,
    ERR_CONVERSION_EXPLICIT_CAST_REQUIRED,
    ERR_RETURN_TYPE_CANT_OVERLOAD,
    ERR_MAIN_OVERLOADED,
    ERR_NO_MATCHING_METHOD,
    ERR_INTERNAL_ERROR,
};

enum warning_code {
    WARN_VARIABLE_UNUSED,
    WARN_FUNCTION_UNUSED,
    WARN_TYPE_UNUSED,
    WARN_PARAMETER_UNUSED,
    WARN_VARIABLE_ASSIGNED_UNUSED,
    WARN_UNREACHABLE_CODE,
    WARN_CAST_UNNEEDED,
};

struct error_info {
    std::string code;
    std::string message;
};

struct error_catalog {
    static const error_info& get_error_info(error_code code) {
        static const error_info errors[] = {
            {"S01", "Identifier expected"},
            {"S02", "'{' expected"},
            {"S03", "'}' expected"},
            {"S04", "'[' expected"},
            {"S05", "']' expected"},
            {"S06", "'(' expected"},
            {"S07", "')' expected"},
            {"S08", "';' expected"},
            {"S09", "Expected module name"},
            {"S10", "Expected parameter type"},
            {"S11", "Expected parameter name"},
            {"S12", "Steel does not support forward declarations"},
            {"S13", "Unexpected token in primary expression"},
            {"S14", "Incomplete escape sequence in literal"},
            {"S15", "Constructor cannot call itself"},
            {"S16", "Expected type name for member"},
            {"S17", "Nested function is not allowed"},
            {"S18", "Parameters cannot be of type void"},
            {"S19", "Function \"%s\" is already defined"},
            {"S20", "Nested constructor is not allowed"},
            {"S21", "Constructor must be defined within a type"},
            {"S22", "Constructor with the same parameters already exists"},
            {"S23", "Variables cannot be of type void"},
            {"S24", "Variable \"%s\" already declared in the same scope"},
            {"S25", "Type \"%s\" is already defined"},
            {"S26", "Nested type declaration is not allowed"},
            {"S27", "Structs cannot contain methods"},
            {"S28", "Interfaces cannot contain constructors"},
            {"S29", "Interfaces cannot contain member variables"},
            {"S30", "Duplicate parameter \"%s\""},
            {"S31", "Unknown identifier \"%s\""},
            {"S32", "Unknown function \"%s\""},
            {"S33", "Unknown type \"%s\""},
            {"S34", "No constructor for type \"%s\" matches argument types provided"},
            {"S35", "Too many values in initializer list"},
            {"S36", "Type mismatch in initializer list"},
            {"S37", "Interface initializer is not allowed"},
            {"S38", "Array initializers are unsupported"},
            {"S39", "Initializer list can only be used with custom types or arrays"},
            {"S40", "Variable of type \"%s\" cannot be assigned a value of type \"%s\""},
            {"S41", "No built-in operator matches the types provided"},
            {"S42", "The type \"%s\" is not defined"},
            {"S43", "Expected member name"},
            {"S44", "The type \"%s\" has no member named \"%s\""},
            {"S45", "No built-in or user-defined operator matches the types provided"},
            {"S46", "Logical NOT operator can only be applied to boolean expressions"},
            {"S47", "NEGATE operator can only be applied to integer or float expressions"},
            {"S48", "Increment operator can only be applied to integer expressions"},
            {"S49", "Decrement operator can only be applied to integer expressions"},
            {"S50", "Base expression is not indexable"},
            {"S51", "Indexer must be an integer expression"},
            {"S52", "No function \"%s\" matches the arguments provided"},
            {"S53", "No constructor for \"%s\" matches the arguments provided"},
            {"S54", "If statement condition must be a boolean expression"},
            {"S55", "For loop condition must be a boolean expression"},
            {"S56", "While loop condition must be a boolean expression"},
            {"S65", "Return statement outside of function or constructor"},
            {"S66", "Constructors cannot return a value"},
            {"S67", "Void function \"%s\" cannot return a value"},
            {"S68", "Function \"%s\" must return a value"},
            {"S69", "Function \"%s\" returns type \"%s\" but got \"%s\""},
            {"S70", "Not all code paths return a value"},
            {"S71", "The type \"%s\" has no method named \"%s\""},
            {"S72", "'this' can only be used inside a non-static method or constructor"},
            {"S78", "Invalid float literal: multiple decimal points"},
            {"S79", "Invalid float literal: no digits after decimal point"},
            {"S80", "Unterminated char literal"},
            {"S81", "Unterminated string literal"},
            {"S82", "Too many characters in char literal"},
            {"S83", "Expected expression"},
            {"S84", "Unexpected identifier"},
            {"S85", "Expected a declaration"},
            {"S86", "Use of uninitialized variable \"%s\""},
            {"S87", "Member access not allowed on non-composite type '%s'"},
            {"S88", "Expected parameter"},
            {"S89", "No built-in or user-defined conversion exists from '%s' to '%s'"},
            {"S90", "Conversion from '%s' to '%s' is explicit, did you forget to use a cast?"},
            {"S91", "Functions or methods cannot be overloaded by return type"},
            {"S92", "Main function cannot be overloaded"},
            {"S93", "No method '%s' matches the arguments provided"},
            {"S94", "An internal compiler error occurred, phase: '%s', message: '%s'"},
        };
        return errors[code];
    }

    static const error_info& get_warning_info(warning_code code) {
        static const error_info warnings[] = {
            {"SW01", "Variable \"%s\" is declared but never used"},
            {"SW02", "Function \"%s\" is declared but never used"},
            {"SW03", "Type \"%s\" is declared but never used"},
            {"SW04", "Parameter \"%s\" is declared but never used"},
            {"SW05", "Variable \"%s\" is assigned a value but never used"},
            {"SW10", "Unreachable code detected"},
            {"SW11", "An implicit cast exists from '%s' to '%s', an explicit cast is not needed"},
        };
        return warnings[code];
    }
};